version: "1.0"
name: 流水线-202608300004
displayName: 流水线-202608300004
stages:
- name: 未命名
  displayName: 未命名
  strategy: naturally
  trigger: auto
  steps:
  - step: build@golang
    name: ea797a21
    displayName: Golang 构建
    golangVersion: "1.24"
    commands:
    - "# 默认使用goproxy.cn\\n export GOPROXY=https://goproxy.cn\\n # 输入你的构建命令 ./build.sh"
    artifacts: []
    caches:
    - /go/pkg/mod
    strategy:
      retry: "0"
      resource:
        cpu: "2"
        memory: "4"
- name: 未命名
  displayName: 未命名
  strategy: naturally
  trigger: auto
  steps:
  - step: publish@general_artifacts
    name: 06d58b02
    displayName: 上传制品
    dependArtifact: BUILD_ARTIFACT
    artifactName: output
    strategy:
      retry: "0"
triggers:
  trigger: auto
  push:
    branches:
      prefix:
      - ""
      precise: []
      include: []
notify: []
