name: 构建并提交
displayName: 构建并提交
stages:
  - name: 构建与提交
      jobs:
            - name: 执行脚本
                    step: shell@agent
                            inputs:
                                      script: |
                                                  chmod +x ./build.sh
                                                              ./build.sh
                                                                          git config user.name "gitee_bot"
                                                                                      git config user.email "bot@gitee.com"
                                                                                                  git add .
                                                                                                              git commit -m "ci: 自动提交编译产物 [skip ci]"
                                                                                                                          git push origin HEAD:${GITEE_BRANCH}