version: "1.0"
name: 测试、构建、上传、发布、部署到自有主机
displayName: 测试、构建、上传、发布、部署到自有主机
stages:
- name: 构建
  displayName: 构建
  strategy: naturally
  trigger: auto
  steps:
  - step: build@golang
    name: _1
    displayName: Golang 构建
    golangVersion: "1.12"
    commands:
    - '# 默认使用goproxy.cn'
    - export GOPROXY=https://goproxy.cn
    - '# 输入你的构建命令'
    - make build
    artifacts:
    - name: BUILD_ARTIFACT
      path:
      - ./output
      type: .tar.gz
    caches:
    - /go/pkg/mod
    notify: []
    strategy:
      retry: "0"
      resource:
        cpu: "2"
        memory: "4"
- name: 上传
  displayName: 上传
  strategy: naturally
  trigger: auto
  steps:
  - step: publish@general_artifacts
    name: _2
    displayName: 上传制品
    dependArtifact: BUILD_ARTIFACT
    artifactName: output
    notify: []
    strategy:
      retry: "0"
      resource:
        cpu: "2"
        memory: "4"
- name: 发布
  displayName: 发布
  strategy: naturally
  trigger: auto
  steps:
  - step: publish@release_artifacts
    name: _3
    displayName: 发布
    dependArtifact: output
    version: 1.0.0.0
    autoIncrement: true
    notify: []
    strategy:
      retry: "0"
      resource:
        cpu: "2"
        memory: "4"
triggers:
  trigger: manual
notify: []
strategy:
  blocking: true
